behaviors:
  Bird:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 1.0e-4
      beta: 1.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10.0e6
    time_horizon: 256
    summary_freq: 5000